openapi: 3.2.0
info:
  description: Documentation of TheTVDB API V4.
  title: TVDB API V4 Artwork Statuses API
  version: 4.7.10
  x-last-validated: '2026-05-30'
  x-spec-source: https://github.com/thetvdb/v4-api/blob/main/docs/swagger.yml
servers:
- url: https://api4.thetvdb.com/v4
  description: TheTVDB v4 API production
security:
- bearerAuth: []
tags:
- name: Artwork Statuses
paths:
  /artwork/statuses:
    get:
      description: Returns list of artwork status records.
      operationId: getAllArtworkStatuses
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/ArtworkStatus'
                    type: array
                  status:
                    type: string
                type: object
              examples:
                GetAllArtworkStatuses200Example:
                  summary: Default getAllArtworkStatuses 200 response
                  x-microcks-default: true
                  value:
                    data:
                    - id: 12345
                      name: Example Name
                    status: Continuing
        '401':
          description: Unauthorized
      tags:
      - Artwork Statuses
      summary: TheTVDB Get All Artwork Statuses
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    ArtworkStatus:
      description: artwork status record
      properties:
        id:
          format: int64
          type: integer
          x-go-name: ID
          example: 12345
        name:
          type: string
          example: Example Name
      type: object
      x-go-package: github.com/whip-networks/tvdb-api-v4-core/tvdb-api-v4-core/pkg/model
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
